openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
  description: Postman Collection for a Todo API
servers:
  - url: '{{baseUrl}}'
paths:
  /todos:
    parameters: []
    post:
      summary: Add Todo
      parameters:
        - name: Content-Type
          in: header
          required: true
          example: application/json
          schema:
            type: string
            minLength: 0
            maxLength: 0
        - name: Accept
          in: header
          required: true
          example: application/json
          schema:
            type: string
            minLength: 0
            maxLength: 0
      responses:
        '201':
          headers:
            Content-Type:
              schema:
                type: string
                minLength: 0
                maxLength: 0
              example: application/json
          description: The created todo
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  task:
                    type: string
                  completed:
                    type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
    get:
      summary: Get Todos
      parameters:
        - name: Accept
          in: header
          required: false
          example: application/json
          schema:
            type: string
      responses:
        '200':
          headers:
            Content-Type:
              schema:
                type: string
              example: application/json
          description: List of all todos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    task:
                      type: string
                    completed:
                      type: boolean
  /todos/{todoid}:
    parameters:
      - name: todoid
        in: path
        required: true
        example: '12345'
        schema:
          type: integer
    get:
      summary: Get Todo
      parameters:
        - name: Accept
          in: header
          required: false
          example: application/json
          schema:
            type: string
      responses: {}
  /todos/{todoId}:
    parameters:
      - name: todoId
        in: path
        required: true
        description: (Required) The id of the todo
        example: abcdefgh-ijkl-1234-5678-mnopqlstuvwx
        schema:
          type: string
    put:
      summary: Update Todo
      parameters:
        - name: Content-Type
          in: header
          required: false
          example: application/json
          schema:
            type: string
        - name: Accept
          in: header
          required: false
          example: application/json
          schema:
            type: string
      responses:
        '200':
          headers:
            Content-Type:
              schema:
                type: string
              example: application/json
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  task:
                    type: string
                  completed:
                    type: boolean
        '404':
          headers: {}
          description: Todo Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                completed:
                  type: boolean
    delete:
      summary: Delete Todo
      parameters: []
      responses:
        '204':
          headers: {}
          description: No Content
        '404':
          headers: {}
          description: Todo Not Found
