openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
  description: OpenAPI Spec for a Todo API
servers:
  - url: '{{baseUrl}}'
paths:
  /todos:
    parameters: []
    post:
      summary: Add Todo
      parameters:
        - name: Content-Type
          in: header
          required: false
          example: application/json
          schema:
            type: string
        - name: Accept
          in: header
          required: false
          example: application/json
          schema:
            type: string
      responses:
        '201':
          headers:
            Content-Type:
              schema:
                type: string
              example: application/json
          description: The created todo
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  task:
                    type: string
                  completed:
                    type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
    get:
      summary: Get Todos
      parameters:
        - name: Accept
          in: header
          required: false
          example: application/json
          schema:
            type: string
      responses:
        '200':
          headers:
            Content-Type:
              schema:
                type: string
              example: application/json
          description: List of all todos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    task:
                      type: string
                    completed:
                      type: boolean
  /todos/{todoid}:
    parameters:
      - name: todoid
        in: path
        required: true
        description: '(Required) '
        example: '12345'
        schema:
          type: integer
    get:
      summary: Get Todo
      parameters: []
      responses:
        '200':
          headers:
            X-Powered-By:
              schema:
                type: string
              example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
              example: '*'
            Content-Type:
              schema:
                type: string
              example: application/json; charset=utf-8
            Content-Length:
              schema:
                type: integer
              example: '26'
            ETag:
              schema:
                type: string
              example: W/"1a-zoKxmrHFn4uaqb4kYUjlWpQ5kYQ"
            Date:
              schema:
                type: string
              example: Wed, 18 Jun 2025 23:10:40 GMT
            Connection:
              schema:
                type: string
              example: keep-alive
            Keep-Alive:
              schema:
                type: string
              example: timeout=5
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  completed:
                    type: boolean
  /todos/{todoId}:
    parameters:
      - name: todoId
        in: path
        required: true
        description: (Required) The id of the todo
        example: abcdefgh-ijkl-1234-5678-mnopqlstuvwx
        schema:
          type: string
    put:
      summary: Update Todo
      parameters:
        - name: Content-Type
          in: header
          required: false
          example: application/json
          schema:
            type: string
        - name: Accept
          in: header
          required: false
          example: application/json
          schema:
            type: string
      responses:
        '200':
          headers:
            Content-Type:
              schema:
                type: string
              example: application/json
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  task:
                    type: string
                  completed:
                    type: boolean
        '404':
          headers: {}
          description: Todo Not Found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                completed:
                  type: boolean
    delete:
      summary: Delete Todo
      parameters: []
      responses:
        '204':
          headers: {}
          description: No Content
        '404':
          headers: {}
          description: Todo Not Found
